server:
  shutdown: graceful
  port: 3000

spring:
  pid:
    file: "dh.pid"
  profiles:
    active:
      - local
    group:
      local:
        - db-local
        - mybatis-local
      dh:
        - db-dh
        - mybatis-dh
    include:
      - datasource
      - mybatis

