spring:
  config:
    activate:
      on-profile: mybatis-local
mybatis:
  configuration:
    map-underscore-to-camel-case: true
#  mapper-locations: classpath:mapper/master/**/*_SQL.xml
#  type-aliases-package: kr.co.seedit.domain
#  config-location: classpath:/mybatis-config.xml
---
spring:
  config:
    activate:
      on-profile: mybatis-dh
mybatis:
  configuration:
    map-underscore-to-camel-case: true
#  mapper-locations: classpath:mapper/master/**/*_SQL.xml
#  type-aliases-package: kr.co.seedit.domain
#  config-location: classpath:/mybatis-config.xml