server:
  shutdown: graceful
  port: 3000

spring:
  pid:
    file: "dh.pid"
  profiles:
    active:
      - local
    group:
      local:
        - db-local
        - mybatis-local
      dh:
        - db-dh
        - mybatis-dh
    include:
      - datasource
      - mybatis

  maildh:
    host: smtp.mailplug.co.kr
    port: 465
    username: euijin.ha@dhpic.co.kr
    password: dhpic11!
    protocol: smtp
    properties:
      starttls: true
      debug: false
      auth: true
      ssl: true
